# Generated by Django 3.0.7 on 2020-06-18 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicios',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Treinos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=20)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='taluno', to='academia.Usuarios')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tprofessor', to='academia.Usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='ExercicioTreino',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('series', models.IntegerField()),
                ('repeticoes', models.IntegerField()),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='treino.Exercicios')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treino.Treinos')),
            ],
        ),
    ]
