# Generated by Django 3.0.7 on 2020-07-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='telefone',
            new_name='convmedico',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='rg',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='urgtel',
            field=models.CharField(default=' ', max_length=15),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='aluno',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='gestor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='professor',
            field=models.BooleanField(default=False),
        ),
    ]
