# Generated by Django 3.0.7 on 2020-07-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_auto_20200701_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='urgtel',
            field=models.CharField(default='', max_length=15),
        ),
    ]
